language: objective-c
osx_image: xcode8.3
script:
 - xcodebuild -workspace SciTuner.xcworkspace -scheme SciTuner -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' build test
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - pod install
